### ISSUE TITLE
Mute SSL errors in non-verbose mode

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#1042]
Sometimes we get error:
```
$ neuro ps
ID  NAME  STATUS  WHEN  IMAGE  OWNER  DESCRIPTION  COMMAND
ERROR: SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x105e525c0>
transport: <_SelectorSocketTransport fd=15 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/mariyadavydova/miniconda3/envs/neuro/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Users/mariyadavydova/miniconda3/envs/neuro/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/Users/mariyadavydova/miniconda3/envs/neuro/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
```
Related aiohttp issue: https://github.com/aio-libs/aiohttp/issues/3535

We want to implement a specific exception handler in NON-verbose mode, which catches this exception and mutes it (see the idea here: https://github.com/aio-libs/aiohttp/issues/3535#issuecomment-483268542)

note: see original discussion: https://neuromation.slack.com/archives/C9Z1UBC6A/p1568022856054600

**Comment by ayushkovskiy** [comment]
I'm not sure how to test it as we get this error occasionally. Probably to be left uncovered.

**Comment by asvetlov** [comment]
I'm fine with uncovered code here.

**Comment by asvetlov** [comment]
Foxed by #1065
