### ISSUE TITLE
Neuro does not work from a job

### ISSUE THREAD

**Issue by ayushkovskiy** [neuromation/platform-client-python#1331]
```
root@job-717fe50a-9c96-42c6-b70d-52a184661fd3:/# neuro --show-traceback --color=no ps
'utf-8' codec can't decode byte 0xb8 in position 27: invalid start byte
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/neuromation/cli/main.py", line 316, in main
    cli.main(args=args, standalone_mode=False)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/neuromation/cli/utils.py", line 194, in wrapper
    debug=root.verbosity >= 2,  # see main:setup_logging for constants
  File "/usr/local/lib/python3.6/dist-packages/neuromation/cli/asyncio_utils.py", line 66, in run
    return loop.run_until_complete(main_task)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/neuromation/cli/utils.py", line 123, in _run_async_function
    await root.init_client()
  File "/usr/local/lib/python3.6/dist-packages/neuromation/cli/root.py", line 70, in init_client
    client = await self._factory.get(timeout=self.timeout)
  File "/usr/local/lib/python3.6/dist-packages/neuromation/api/config_factory.py", line 73, in get
    saved_config = config = self._read()
  File "/usr/local/lib/python3.6/dist-packages/neuromation/api/config_factory.py", line 225, in _read
    payload = yaml.safe_load(f)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 70, in load
    loader = Loader(stream)
  File "/usr/lib/python3/dist-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/usr/lib/python3/dist-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/lib/python3/dist-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/usr/lib/python3/dist-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 27: invalid start byte

```

**Comment by ayushkovskiy** [comment]
Reproducible for `Neuro Platform Client 19.12.19`. The problem does not exist for `Neuro Platform Client 20.01.22`. closing.
