### ISSUE TITLE
Error during cleanup

### ISSUE THREAD

**Issue by adavydow** [neuromation/platform-client-python#616]
I faced the following error while working with neuro in Windows environment.
It's not easily reproducible, but happens from time to time.
I'm not sure if other platforms are affected (never saw this error on Mac)

```
neuro exec job-7486e7a7-1586-49fc-9ec9-0f52e0654199 -t bash
root@job-7486e7a7-1586-49fc-9ec9-0f52e0654199:/# ls
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
root@job-7486e7a7-1586-49fc-9ec9-0f52e0654199:/# exit
exit
Connection to ssh-auth-dev.neu.ro closed.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002F76015FD08>
Traceback (most recent call last):
  File "d:\conda\envs\neurocli37\lib\asyncio\proactor_events.py", line 95, in __del__
    self.close()
  File "d:\conda\envs\neurocli37\lib\asyncio\proactor_events.py", line 86, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "d:\conda\envs\neurocli37\lib\asyncio\base_events.py", line 688, in call_soon
    self._check_closed()
  File "d:\conda\envs\neurocli37\lib\asyncio\base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by asvetlov** [comment]
Outdated
